name = input("Enter student name: ")
course = input("Enter course: ")
admission_number = input("Enter admission number: ")
institution = input("Enter institution: ")
total_marks = input("Enter total marks obtained: ")
print("student name: " + name)
print("course: " + course)
print("admission number: " + admission_number)
print("institution: " + institution)
print("total marks: " + total_marks)
print("===========================")
print("status:PASS -promoted")
print("=======================")