name = input("what is your name: ")
admission_number = input("what is your admission number: ")
instituion = input("what is the name of your instituion: ")
course = input("which course are you enrolled in: ")
units = input("which units are you enrolled in: ")
age = input("what is your age:")
favourite_programming_language = input("which programming language do you like most: ")
print("student name:", name)
print("admission number:", admission_number)
print("institution name:", instituion)
print("course:", course)
print("units:", units)
print("age:", age)
print("favourite programming language:", favourite_programming_language)